---
# tasks file for roles/ocp_create_ns
- name: Create a k8s namespace
  k8s:
    name: sock-shop
    api_version: v1
    kind: Namespace
    state: present

- name: get openshift git deployment repo
  git:
    repo: https://github.com/HaaikeV/sock-shop-ocp-ws.git
    dest: .
    version: master  

- name: Read Definition file
  k8s:
    state: present
    definition: "{{ lookup('file', 'complete-demo.yaml') | from_yaml }}"