---
# tasks file for roles/ocp_create_ns
#- name: Create a k8s namespace
#  k8s:
#    name: hvanderm-dev
#    api_version: v1
#    kind: Namespace
#    state: present

- name: Read Definition file
  k8s:
    state: present
    definition: "{{ lookup('file', 'complete-demo.yaml') | from_yaml }}"