---
# tasks file for roles/ocp_create_ns
- name: Create a k8s namespace
  k8s:
    name: sock-shop
    api_version: v1
    kind: Namespace
    state: present

- name: get openshift git deployment repo
  git:
    repo: https://github.com/HaaikeV/sock-shop-ocp-ws.git
    dest: /tmp/repo_dump/
    version: main  

- name: Read Definition file
  k8s:
    state: present
    src: /tmp/repo_dump/deploy/kubernetes/complete-demo.yaml